name: Quality Check - Evaluations

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  quality-gate:
    uses: ./.github/workflows/_quality-module.yml
    with:
      module: evaluations
      unit_task: test:unit:evaluations
      integration_task: test:integration:evaluations
    secrets: inherit
