name: Quality Check - Students

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  quality-gate:
    uses: ./.github/workflows/_quality-module.yml
    with:
      module: students
      unit_task: test:unit:students
      integration_task: test:integration:students
    secrets: inherit
